name: Docker Image CI

on:
  push:
    branches: ["master"]

jobs:
  test-push: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Build the test Docker image
      run: docker build . --file Dockerfile -t bluero/shops-service:latest



    - name: Run Docker container
      run: docker run -p 8000:80 -d bluero/shops-service:latest

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
      
    - name: Install packages
      run: pip install pytest requests
    
    - name: Run tests
      run: pytest
        


    - name: Login into Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push tag to Docker Hub
      run: docker push bluero/shops-service:latest